name: .NET Version Bump
run-name: Bump version to v${{ inputs.versionTag }} by ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      initials:
        description: 'Developers Initials'
        required: true
        type: string
      versionTag:
        description: 'Create Version'
        required: true
        type: string
env:
    BRANCH: feature/${{ inputs.initials }}-version-${{ inputs.versionTag }}
    COMMIT_MESSAGE: Bump version to v${{ inputs.versionTag }}
    VERSION_TAG: ${{ inputs.versionTag }}
    GITHUB_TOKEN: ${{ secrets.TEST_COMMIT_TOKEN }}
jobs:
    build-and-deploy-dotnet-app:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          with: 
            fetch-depth: 0
            token: ${{ secrets.TEST_COMMIT_TOKEN }}

        - name: Version Bump in .csproj
          run: |
            sed -i 's|<VersionPrefix>.*</VersionPrefix>|<VersionPrefix>${{ env.VERSION_TAG }}</VersionPrefix>|g' *.csproj

        - name: Create New Branch
          run: |
            git checkout -b ${{ env.BRANCH }}

        - name: Commit Changes
          run: |
            git checkout ${{ env.BRANCH }}
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git config --global user.name ${{ github.actor }}
            git add .
            git commit -m "Bump version to ${{ env.VERSION_TAG }}"
            git push

        - name: Create Pull Request
          run: >
            gh pr create
            --base main
            --head ${{ env.BRANCH }}
            --fill
