name: Count Controllers and Operations
run-name: Run at ${{ github.created_at }}

on:
  # allow the workflow to be triggered manually
  workflow_dispatch:

  # allow the workflow to be called from another workflow
  workflow_call:

jobs:
  display-time:
    name: Display Current EST Time
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
