name: Count Controllers and Operations

run-name: Report Pulled on - requested by ${{ github.actor }}

on:
  # allow the workflow to be triggered manually
  workflow_dispatch:

  # allow the workflow to be called from another workflow
  workflow_call:

jobs:
  display-time:
    name: Display Current EST Time
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Current EST Time
        id: est-time
        run: |
          # Get current UTC time and convert it to Eastern Standard Time (EST)
          $utcNow = (Get-Date).ToUniversalTime()
          $estZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("Eastern Standard Time")
          $estNow = [System.TimeZoneInfo]::ConvertTimeFromUtc($utcNow, $estZone)
          Write-Output "::set-output name=estTime::$(($estNow).ToString('yyyy-MM-dd HH:mm:ss'))"

      - name: Set Run Name with EST Time
        run: echo "Current Run Name ${{ github.workflow }} at ${{ steps.est-time.outputs.estTime }} EST"

    outputs:
      run-name: "Run at ${{ steps.est-time.outputs.estTime }} EST"
